var selectHTML = '';
const states = [
  {
    State: 'Andhra Pradesh',
    District: [
      'Anantapur',
      'Chittoor',
      'East Godavari',
      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
      'SriPotti Sri Ramulu Nellore',
      'Vishakhapatnam',
      'Vizianagaram',
      'West Godavari',
      'Cudappah',
    ]
  },
  {
    State: 'Arunachal Pradesh',
    District: [
      'Anjaw',
      'Changlang',
      'Dibang Valley',
      'East Siang',
      'East Kameng',
      'Kurung Kumey',
      'Lohit',
      'Longding',
      'Lower Dibang Valley',
      'Lower Subansiri',
      'Papum Pare',
      'Tawang',
      'Tirap',
      'Upper Siang',
      'Upper Subansiri',
      'West Kameng',
      'West Siang',
    ]
  },
  {
    State: 'Assam',
    District: [
      'Baksa',
      'Barpeta',
      'Bongaigaon',
      'Cachar',
      'Chirang',
      'Darrang',
      'Dhemaji',
      'Dima Hasao',
      'Dhubri',
      'Dibrugarh',
      'Goalpara',
      'Golaghat',
      'Hailakandi',
      'Jorhat',
      'Kamrup',
      'Kamrup Metropolitan',
      'Karbi Anglong',
      'Karimganj',
      'Kokrajhar',
      'Lakhimpur',
      'Morigaon',
      'Nagaon',
      'Nalbari',
      'Sivasagar',
      'Sonitpur',
      'Tinsukia',
      'Udalguri',
    ]
  },
  {
    State: 'Bihar',
    District: [
      'Araria',
      'Arwal',
      'Aurangabad',
      'Banka',
      'Begusarai',
      'Bhagalpur',
      'Bhojpur',
      'Buxar',
      'Darbhanga',
      'East Champaran',
      'Gaya',
      'Gopalganj',
      'Jamui',
      'Jehanabad',
      'Kaimur',
      'Katihar',
      'Khagaria',
      'Kishanganj',
      'Lakhisarai',
      'Madhepura',
      'Madhubani',
      'Munger',
      'Muzaffarpur',
      'Nalanda',
      'Nawada',
      'Patna',
      'Purnia',
      'Rohtas',
      'Saharsa',
      'Samastipur',
      'Saran',
      'Sheikhpura',
      'Sheohar',
      'Sitamarhi',
      'Siwan',
      'Supaul',
      'Vaishali',
      'West Champaran',
    ]
  },
  {
    State: 'Chhattisgarh',
    District: [
      'Bastar',
      'Bijapur',
      'Bilaspur',
      'Dantewada',
      'Dhamtari',
      'Durg',
      'Jashpur',
      'Janjgir-Champa',
      'Korba',
      'Koriya',
      'Kanker',
      'Kabirdham (formerly Kawardha)',
      'Mahasamund',
      'Narayanpur',
      'Raigarh',
      'Rajnandgaon',
      'Raipur',
      'Surajpur',
      'Surguja',
    ]
  },
  { State: 'Dadra and Nagar Haveli', District: ['Amal', 'Silvassa'] },
  { State: 'Daman and Diu', District: ['Daman', 'Diu'] },
  {
    State: 'Delhi',
    District: [
      'Delhi',
      'New Delhi',
      'North Delhi',
      'Noida',
      'Patparganj',
      'Sonabarsa',
      'Tughlakabad',
    ]
  },
  {
    State: 'Goa',
    District: [
      'Chapora',
      'Dabolim',
      'Madgaon',
      'Marmugao (Marmagao)',
      'Panaji Port',
      'Panjim',
      'Pellet Plant Jetty/Shiroda',
      'Talpona',
      'Vasco da Gama',
    ]
  },
  {
    State: 'Gujarat',
    District: [
      'Ahmedabad',
      'Amreli district',
      'Anand',
      'Aravalli',
      'Banaskantha',
      'Bharuch',
      'Bhavnagar',
      'Dahod',
      'Dang',
      'Gandhinagar',
      'Jamnagar',
      'Junagadh',
      'Kutch',
      'Kheda',
      'Mehsana',
      'Narmada',
      'Navsari',
      'Patan',
      'Panchmahal',
      'Porbandar',
      'Rajkot',
      'Sabarkantha',
      'Surendranagar',
      'Surat',
      'Tapi',
      'Vadodara',
      'Valsad',
    ]
  },
  {
    State: 'Haryana',
    District: [
      'Ambala',
      'Bhiwani',
      'Faridabad',
      'Fatehabad',
      'Gurgaon',
      'Hissar',
      'Jhajjar',
      'Jind',
      'Karnal',
      'Kaithal',
      'Kurukshetra',
      'Mahendragarh',
      'Mewat',
      'Palwal',
      'Panchkula',
      'Panipat',
      'Rewari',
      'Rohtak',
      'Sirsa',
      'Sonipat',
      'Yamuna Nagar',
    ]
  },
  {
    State: 'Himachal Pradesh',
    District: [
      'Baddi',
      'Baitalpur',
      'Chamba',
      'Dharamsala',
      'Hamirpur',
      'Kangra',
      'Kinnaur',
      'Kullu',
      'Lahaul & Spiti',
      'Mandi',
      'Simla',
      'Sirmaur',
      'Solan',
      'Una',
    ]
  },
  {
    State: 'Jammu and Kashmir',
    District: ['Jammu', 'Leh', 'Rajouri', 'Srinagar'],
  },
  {
    State: 'Jharkhand',
    District: [
      'Bokaro',
      'Chatra',
      'Deoghar',
      'Dhanbad',
      'Dumka',
      'East Singhbhum',
      'Garhwa',
      'Giridih',
      'Godda',
      'Gumla',
      'Hazaribag',
      'Jamtara',
      'Khunti',
      'Koderma',
      'Latehar',
      'Lohardaga',
      'Pakur',
      'Palamu',
      'Ramgarh',
      'Ranchi',
      'Sahibganj',
      'Seraikela Kharsawan',
      'Simdega',
      'West Singhbhum',
    ]
  },
  {
    State: 'Karnataka',
    District: [
      'Bagalkot',
      'Bangalore',
      'Bangalore Urban',
      'Belgaum',
      'Bellary',
      'Bidar',
      'Bijapur',
      'Chamarajnagar',
      'Chikkamagaluru',
      'Chikkaballapur',
      'Chitradurga',
      'Davanagere',
      'Dharwad',
      'Dakshina Kannada',
      'Gadag',
      'Gulbarga',
      'Hassan',
      'Haveri district',
      'Kodagu',
      'Kolar',
      'Koppal',
      'Mandya',
      'Mysore',
      'Raichur',
      'Shimoga',
      'Tumkur',
      'Udupi',
      'Uttara Kannada',
      'Ramanagara',
      'Yadgir',
    ]
  },
  {
    State: 'Kerala',
    District: [
      'Alappuzha',
      'Ernakulam',
      'Idukki',
      'Kannur',
      'Kasaragod',
      'Kollam',
      'Kottayam',
      'Kozhikode',
      'Malappuram',
      'Palakkad',
      'Pathanamthitta',
      'Thrissur',
      'Thiruvananthapuram',
      'Wayanad',
    ]
  },
  {
    State: 'Madhya Pradesh',
    District: [
      'Alirajpur',
      'Anuppur',
      'Ashoknagar',
      'Balaghat',
      'Barwani',
      'Betul',
      'Bhilai',
      'Bhind',
      'Bhopal',
      'Burhanpur',
      'Chhatarpur',
      'Chhindwara',
      'Damoh',
      'Dewas',
      'Dhar',
      'Guna',
      'Gwalior',
      'Hoshangabad',
      'Indore',
      'Itarsi',
      'Jabalpur',
      'Khajuraho',
      'Khandwa',
      'Khargone',
      'Malanpur',
      'Malanpuri (Gwalior)',
      'Mandla',
      'Mandsaur',
      'Morena',
      'Narsinghpur',
      'Neemuch',
      'Panna',
      'Pithampur',
      'Raipur',
      'Raisen',
      'Ratlam',
      'Rewa',
      'Sagar',
      'Satna',
      'Sehore',
      'Seoni',
      'Shahdol',
      'Singrauli',
      'Ujjain',
    ]
  },
  {
    State: 'Maharastra',
    District: [
      'Ahmednagar',
      'Akola',
      'Alibag',
      'Amaravati',
      'Arnala',
      'Aurangabad',
      'Aurangabad',
      'Bandra',
      'Bassain',
      'Belapur',
      'Bhiwandi',
      'Bhusaval',
      'Borliai-Mandla',
      'Chandrapur',
      'Dahanu',
      'Daulatabad',
      'Dighi (Pune)',
      'Dombivali',
      'Goa',
      'Jaitapur',
      'Jalgaon',
      'Jawaharlal Nehru (Nhava Sheva)',
      'Kalyan',
      'Karanja',
      'Kelwa',
      'Khopoli',
      'Kolhapur',
      'Lonavale',
      'Malegaon',
      'Malwan',
      'Manori',
      'Mira Bhayandar',
      'Miraj',
      'Mumbai (ex Bombay)',
      'Murad',
      'Nagapur',
      'Nagpur',
      'Nalasopara',
      'Nanded',
      'Nandgaon',
      'Nasik',
      'Navi Mumbai',
      'Nhave',
      'Osmanabad',
      'Palghar',
      'Panvel',
      'Pimpri',
      'Pune',
      'Ratnagiri',
      'Sholapur',
      'Shrirampur',
      'Shriwardhan',
      'Tarapur',
      'Thana',
      'Thane',
      'Trombay',
      'Varsova',
      'Vengurla',
      'Virar',
      'Wada',
    ]
  },
  {
    State: 'Manipur',
    District: [
      'Bishnupur',
      'Churachandpur',
      'Chandel',
      'Imphal East',
      'Senapati',
      'Tamenglong',
      'Thoubal',
      'Ukhrul',
      'Imphal West',
    ]
  },
  {
    State: 'Meghalaya',
    District: [
      'Baghamara',
      'Balet',
      'Barsora',
      'Bolanganj',
      'Dalu',
      'Dawki',
      'Ghasuapara',
      'Mahendraganj',
      'Moreh',
      'Ryngku',
      'Shella Bazar',
      'Shillong',
    ]
  },
  {
    State: 'Mizoram',
    District: [
      'Aizawl',
      'Champhai',
      'Kolasib',
      'Lawngtlai',
      'Lunglei',
      'Mamit',
      'Saiha',
      'Serchhip',
    ]
  },
  {
    State: 'Nagaland',
    District: [
      'Dimapur',
      'Kiphire',
      'Kohima',
      'Longleng',
      'Mokokchung',
      'Mon',
      'Peren',
      'Phek',
      'Tuensang',
      'Wokha',
      'Zunheboto',
    ]
  },
  {
    State: 'Odisha',
    District: [
      'Bahabal Pur',
      'Bhubaneswar',
      'Chandbali',
      'Gopalpur',
      'Jeypore',
      'Paradip Garh',
      'Puri',
      'Rourkela',
    ]
  },
  {
    State: 'Puducherry',
    District: ['Karaikal', 'Mahe', 'Pondicherry', 'Yanam']
  },
  {
    State: 'Punjab',
    District: [
      'Amritsar',
      'Barnala',
      'Bathinda',
      'Firozpur',
      'Faridkot',
      'Fatehgarh Sahib',
      'Fazilka',
      'Gurdaspur',
      'Hoshiarpur',
      'Jalandhar',
      'Kapurthala',
      'Ludhiana',
      'Mansa',
      'Moga',
      'Sri Muktsar Sahib',
      'Pathankot',
      'Patiala',
      'Rupnagar',
      'Ajitgarh (Mohali)',
      'Sangrur',
      'Shahid Bhagat Singh Nagar',
      'Tarn Taran',
    ]
  },
  {
    State: 'Rajasthan',
    District: [
      'Ajmer',
      'Banswara',
      'Barmer',
      'Barmer Rail Station',
      'Basni',
      'Beawar',
      'Bharatpur',
      'Bhilwara',
      'Bhiwadi',
      'Bikaner',
      'Bongaigaon',
      'Boranada, Jodhpur',
      'Chittaurgarh',
      'Fazilka',
      'Ganganagar',
      'Jaipur',
      'Jaipur-Kanakpura',
      'Jaipur-Sitapura',
      'Jaisalmer',
      'Jodhpur',
      'Jodhpur-Bhagat Ki Kothi',
      'Jodhpur-Thar',
      'Kardhan',
      'Kota',
      'Munabao Rail Station',
      'Nagaur',
      'Rajsamand',
      'Sawaimadhopur',
      'Shahdol',
      'Shimoga',
      'Tonk',
      'Udaipur',
    ]
  },
  { State: 'Sikkim', Disrtict: ['Chamurci', 'Gangtok'] },
  {
    State: 'Tamilnadu',
    District: [
      'Ariyalur',
      'Chennai',
      'Coimbatore',
      'Cuddalore',
      'Dharmapuri',
      'Dindigul',
      'Erode',
      'Kanchipuram',
      'Kanyakumari',
      'Karur',
      'Krishnagiri',
      'Madurai',
      'Mandapam',
      'Nagapattinam',
      'Nilgiris',
      'Namakkal',
      'Perambalur',
      'Pudukkottai',
      'Ramanathapuram',
      'Salem',
      'Sivaganga',
      'Thanjavur',
      'Thiruvallur',
      'Tirupur',
      'Tiruchirapalli',
      'Theni',
      'Tirunelveli',
      'Thanjavur',
      'Thoothukudi',
      'Tiruvallur',
      'Tiruvannamalai',
      'Vellore',
      'Villupuram',
      'Viruthunagar',
    ]
  },
  {
    State: 'Telangana',
    District: [
      'Adilabad',
      'Hyderabad',
      'Karimnagar',
      'Mahbubnagar',
      'Medak',
      'Nalgonda',
      'Nizamabad',
      'Ranga Reddy',
      'Warangal',
    ]
  },
  {
    State: 'Tiripura',
    District: [
      'Agartala',
      'Dhalaighat',
      'Kailashahar',
      'Kamalpur',
      'Kanchanpur',
      'Kel Sahar Subdivision',
      'Khowai',
      'Khowaighat',
      'Mahurighat',
      'Old Raghna Bazar',
      'Sabroom',
      'Srimantapur',
    ]
  },
  {
    State: 'Uttar Pradesh',
    District: [
      'Agra',
      'Allahabad',
      'Auraiya',
      'Banbasa',
      'Bareilly',
      'Berhni',
      'Bhadohi',
      'Dadri',
      'Dharchula',
      'Gandhar',
      'Gauriphanta',
      'Ghaziabad',
      'Gorakhpur',
      'Gunji',
      'Jarwa',
      'Jhulaghat (Pithoragarh)',
      'Kanpur',
      'Katarniyaghat',
      'Khunwa',
      'Loni',
      'Lucknow',
      'Meerut',
      'Moradabad',
      'Muzaffarnagar',
      'Nepalgunj Road',
      'Pakwara (Moradabad)',
      'Pantnagar',
      'Saharanpur',
      'Sonauli',
      'Surajpur',
      'Tikonia',
      'Varanasi',
    ]
  },
  {
    State: 'Uttarakhand',
    District: [
      'Almora',
      'Badrinath',
      'Bangla',
      'Barkot',
      'Bazpur',
      'Chamoli',
      'Chopra',
      'Dehra Dun',
      'Dwarahat',
      'Garhwal',
      'Haldwani',
      'Hardwar',
      'Haridwar',
      'Jamal',
      'Jwalapur',
      'Kalsi',
      'Kashipur',
      'Mall',
      'Mussoorie',
      'Nahar',
      'Naini',
      'Pantnagar',
      'Pauri',
      'Pithoragarh',
      'Rameshwar',
      'Rishikesh',
      'Rohni',
      'Roorkee',
      'Sama',
      'Saur',
    ]
  },
  {
    State: 'West Bengal',
    District: [
      'Alipurduar',
      'Bankura',
      'Bardhaman',
      'Birbhum',
      'Cooch Behar',
      'Dakshin Dinajpur',
      'Darjeeling',
      'Hooghly',
      'Howrah',
      'Jalpaiguri',
      'Kolkata',
      'Maldah',
      'Murshidabad',
      'Nadia',
      'North 24 Parganas',
      'Paschim Medinipur',
      'Purba Medinipur',
      'Purulia',
      'South 24 Parganas',
      'Uttar Dinajpur',
    ]
  }
];
state();
function state() {
  for (let stateName of states) {
    selectHTML = "<option value='" +stateName.State +"'>" + stateName.State + "</option>";
    var newSelect = document.createElement('option');
    newSelect.innerHTML = selectHTML;
    document.getElementById('State').add(newSelect);
  }
}
document.getElementById('State').addEventListener('change', function () {
  if (this.value) {
    loadDistrict(this.value);
  }
});
function loadDistrict(selectedStateName) {
  var selectedState = states.filter((stateItem) => {
    return selectedDistrict === stateItem.State;
  });

  const districts =
    selectedState && selectedState[0] ? selectedState[0].District : [];
  document.getElementById('District').innerHTML=null;
  if (districts && districts.length > 0) {
    selectHTML = "<option value='" + '' + "'>" + '--Select--' + '</option>';
    var newSelect = document.createElement('option');
    newSelect.innerHTML = selectHTML;
    document.getElementById('District').add(newSelect);
    for (let districtName of districts) {
      selectHTML =
        "<option value='" + districtName + "'>" + districtName + '</option>';
      var newSelect = document.createElement('option');
      newSelect.innerHTML = selectHTML;
      document.getElementById('District').add(newSelect);
    }
  }
}
